@startuml

' Определение классов (таблиц)
class Товары {
    +id: int
    +title: varchar(255)
    +slug: varchar(150)
    +description: text
    +category: int
    +sku: varchar(255)
    +barcode: varchar(255)
    +manufacturer_countries: varchar(255)
    +brand: int
    +vendor: varchar(255)
    +vendor_code: varchar(255)
    +length: decimal(10,2)
    +width: decimal(10,2)
    +height: decimal(10,2)
    +weight: decimal(10,2)
    +price: decimal(20,2)
    +quantity: int
    +supplier: int
    +supplier_sku: int
    +supplier_url: varchar(200)
    +supplier_price: int
    +publish: boolean
    +author: int
    +created: datetime
    +updated: datetime
    +image: varchar(100)
}

class Фотографии_товаров {
    +id: int
    +product: int
    +image: varchar(100)
    +alt: varchar(255)
    +order: int
}

class Списки_категорий {
    +id: int
    +title: varchar(50)
    +slug: varchar(150)
    +parent: int
}

class Списки_поставщиков {
    +id: int
    +name: varchar(255)
    +site: varchar(200)
    +first_name: varchar(50)
    +last_name: varchar(50)
    +email: varchar(254)
    +phone: varchar(50)
    +address: varchar(250)
    +comment: text
    +markup: decimal(10,2)
}

class Поставки {
    +id: int
    +id_supply: int
    +supplier: int
    +responsible: int
    +act_number: varchar(5)
    +comment: text
}

class Список_товаров_в_поставке {
    +id: int
    +supply: int
    +product: int
    +quantity: int
}

class Списки_брендов {
    +id: int
    +name: varchar(255)
    +description: text
}

class Заказы {
    +id: int
    +user: int
    +first_name: varchar(50)
    +last_name: varchar(50)
    +phone_number: varchar(12)
    +email: varchar(254)
    +address: varchar(250)
    +postal_code: varchar(20)
    +city: varchar(100)
    +comment: text
    +created: datetime
    +updated: datetime
    +paid: boolean
    +self_pickup: boolean
    +courier_delivery: boolean
    +status: varchar(32)
}

class Товары_из_заказа {
    +id: int
    +order: int
    +product: int
    +quantity: int
    +price: decimal(20,2)
}

class Корзина {
    +id: int
    +user: int
    +created_at: datetime
}

class Товары_из_корзины {
    +id: int
    +cart: int
    +product: int
    +quantity: int
}

class Платежи {
    +id: int
    +amount: decimal(10,2)
    +currency: varchar(3)
    +created_at: datetime
    +updated_at: datetime
}

class Обращение_покупателей {
    +id: int
    +name: varchar(100)
    +email: varchar(254)
    +message: text
    +created_at: datetime
    +status: varchar(10)
}

class Отчеты {
    +id: int
    +name: varchar(255)
    +created_at: datetime
}

' Определение связей между таблицами
Товары "1" -- "*" Фотографии_товаров : has >
Товары "1" -- "*" Список_товаров_в_поставке : has >
Товары "1" -- "*" Товары_из_заказа : has >
Товары "1" -- "*" Товары_из_корзины : has >
Товары "1" -- "1" Списки_категорий : belongs to >
Товары "1" -- "1" Списки_поставщиков : supplied by >
Товары "1" -- "1" Списки_брендов : has >
Заказы "1" -- "*" Товары_из_заказа : contains >
Заказы "1" -- "*" Платежи : has >
Корзина "1" -- "*" Товары_из_корзины : contains >
Поставки "1" -- "*" Список_товаров_в_поставке : contains >
Поставки "1" -- "1" Списки_поставщиков : supplied by >
Поставки "1" -- "1" User : responsible for >
Заказы "1" -- "1" User : placed by >
Корзина "1" -- "1" User : belongs to >
Обращение_покупателей "1" -- "1" User : belongs to >
Отчеты "1" -- "*" Заказы : supplied by <

' Убираем зеленые значки у названий таблиц
hide Товары circle
hide Фотографии_товаров circle
hide Списки_категорий circle
hide Списки_поставщиков circle
hide Поставки circle
hide Список_товаров_в_поставке circle
hide Списки_брендов circle
hide Заказы circle
hide Товары_из_заказа circle
hide Корзина circle
hide Товары_из_корзины circle
hide Платежи circle
hide Обращение_покупателей circle
hide Отчеты circle

' Убираем значки у списков в таблицах
hide Товары methods
hide Фотографии_товаров methods
hide Списки_категорий methods
hide Списки_поставщиков methods
hide Поставки methods
hide Список_товаров_в_поставке methods
hide Списки_брендов methods
hide Заказы methods
hide Товары_из_заказа methods
hide Корзина methods
hide Товары_из_корзины methods
hide Платежи methods
hide Обращение_покупателей methods
hide Отчеты methods

@enduml