# Generated by Django 5.1b1 on 2024-08-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_productcategory_ozon_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, verbose_name=',Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Партномер'),
        ),
    ]
