# Generated by Django 5.1b1 on 2024-08-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_options_remove_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Бренд'),
        ),
    ]
