# Generated by Django 5.1b1 on 2024-08-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_category_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=11, verbose_name='Номер телефона'),
        ),
    ]
