# Generated by Django 5.1b1 on 2024-09-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_product_size_l_remove_product_size_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='size_l',
            field=models.BooleanField(default=False, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_m',
            field=models.BooleanField(default=False, verbose_name='M'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_one_size',
            field=models.BooleanField(default=False, verbose_name='One Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_s',
            field=models.BooleanField(default=False, verbose_name='S'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_xl',
            field=models.BooleanField(default=False, verbose_name='XL'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_xs',
            field=models.BooleanField(default=False, verbose_name='XS'),
        ),
    ]
