# Generated by Django 5.1b1 on 2024-09-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_product_sizes_product_size_l_product_size_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=255, verbose_name='Размеры'),
        ),
    ]
