# Generated by Django 5.1b1 on 2024-09-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_one_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество товара (One size)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_l',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество (L)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_m',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество (M)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_s',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество (S)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_xl',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество (XL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_xs',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество (XS)'),
        ),
    ]
