# Generated by Django 5.1b1 on 2024-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_remove_product_size_one_size_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_one_size',
            field=models.BooleanField(default=False, verbose_name='Товар без размера'),
        ),
    ]
