# Generated by Django 5.1b1 on 2024-09-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_product_is_one_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_one_size',
        ),
    ]
