# Generated by Django 5.1b1 on 2024-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_orderitem_size_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_m',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_s',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_xl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_xs',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество товара'),
        ),
    ]
