# Generated by Django 5.1b1 on 2024-09-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_customeruser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerUser',
            new_name='BuyerProfile',
        ),
    ]
