# Generated by Django 5.1b1 on 2024-09-16 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_rename_customeruser_buyerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'verbose_name': 'Профиль покупателя', 'verbose_name_plural': 'Профили покупателей'},
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
