# Generated by Django 5.1b1 on 2024-09-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_order_courier_delivery_order_self_pickup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='supplier',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
