# Generated by Django 5.1b1 on 2024-09-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_published',
        ),
    ]
