# Generated by Django 5.1b1 on 2024-09-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_orderitem_product_id_value_orderitem_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
