# Generated by Django 5.1b1 on 2024-09-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_remove_orderitem_discount_remove_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Итого'),
        ),
    ]
