# Generated by Django 5.1b1 on 2024-09-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_orderitem_cena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cena',
            new_name='total_price',
        ),
    ]
