# Generated by Django 5.1b1 on 2024-09-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_rename_cena_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
