# Generated by Django 5.1b1 on 2024-09-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_remove_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары из заказа'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id_value',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_title',
        ),
    ]
