# Generated by Django 5.1b1 on 2024-09-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_alter_supply_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='number',
        ),
    ]
