# Generated by Django 5.1b1 on 2024-09-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_remove_supply_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='id_supply',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Номер поставки'),
            preserve_default=False,
        ),
    ]
