# Generated by Django 5.1b1 on 2024-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Выгрузку отчета по заказам', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конечная дата'),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начальная дата'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='Название отчета'),
        ),
        migrations.AddField(
            model_name='report',
            name='statuses',
            field=models.ManyToManyField(blank=True, to='shop.orderstatus', verbose_name='Статусы заказов'),
        ),
    ]
